# AgenticX 深度搜索系统配置文件
# Deep Search System Configuration

# LLM 提供者配置
llm:
  provider: "kimi"  # 支持: kimi, openai, anthropic, azure
  model: "kimi-k2-0711-preview"
  api_key: "${KIMI_API_KEY}"  # 从环境变量读取
  base_url: "${KIMI_API_BASE}"  # 支持代理设置
  temperature: 0.7
  max_tokens: 4000
  timeout: 300.0  # 增加到300秒（5分钟）
  max_retries: 3

# 搜索引擎配置
search:
  provider: "bochaai"  # 支持: google, bing, bochaai, mock
  google:
    api_key: "${GOOGLE_API_KEY}"
    fallback_api_key: "${GEMINI_API_KEY}"
    search_engine_id: "${GOOGLE_SEARCH_ENGINE_ID}"
    max_results: 10
  bing:
    subscription_key: "${BING_SUBSCRIPTION_KEY}"
    endpoint: "https://api.bing.microsoft.com/v7.0/search"
    market: "zh-CN"
    safe_search: "Moderate"
    max_results: 1
  bochaai:
    api_key: "${BOCHAAI_API_KEY}"
    endpoint: "https://api.bochaai.com/v1/web-search"
    market: "zh-CN"
    max_results: 1
  mock:
    delay: 1.0  # 模拟搜索延迟
    max_results: 5

# 深度搜索配置
deep_search:
  max_research_loops: 1  # 最大研究迭代次数
  max_search_results: 10  # 每次搜索的最大结果数
  max_generated_search_query_per_research_loop: 3  # 每次研究循环生成的最大查询数
  quality_threshold: 0.8  # 质量阈值
  convergence_threshold: 0.95  # 收敛阈值
  content_analysis_depth: "detailed"  # 内容分析深度: basic, detailed, comprehensive
  enable_reflection: true  # 启用反思机制
  enable_knowledge_gap_detection: true  # 启用知识空白检测
  enable_source_validation: true  # 启用来源验证
  initial_query_count: 3
  followup_query_count: 2
  
# 查询生成配置
query_generation:
  strategies:
    - "broad_exploration"  # 广泛探索
    - "focused_deep_dive"  # 聚焦深入
    - "gap_filling"  # 填补空白
    - "cross_validation"  # 交叉验证
  max_queries_per_iteration: 5
  query_diversity_threshold: 0.7
  enable_multilingual: true
  languages: ["zh", "en"]  # 支持的语言

# 内容分析配置
content_analysis:
  extract_entities: true  # 提取实体
  extract_relationships: true  # 提取关系
  sentiment_analysis: false  # 情感分析
  topic_modeling: true  # 主题建模
  summarization_method: "extractive"  # 摘要方法: extractive, abstractive
  max_summary_length: 500

# 知识提取配置
knowledge_extraction:
  extract_facts: true  # 提取事实
  extract_concepts: true  # 提取概念
  extract_procedures: true  # 提取流程
  confidence_threshold: 0.7  # 置信度阈值
  enable_fact_verification: true  # 启用事实验证

# 来源验证配置
source_validation:
  check_authority: true  # 检查权威性
  check_recency: true  # 检查时效性
  check_relevance: true  # 检查相关性
  check_credibility: true  # 检查可信度
  authority_threshold: 0.7
  recency_threshold_days: 365
  relevance_threshold: 0.8
  credibility_threshold: 0.7

# 报告生成配置
report_generation:
  format: "markdown"  # 支持: markdown, html, json, txt
  include_citations: true  # 包含引用
  include_methodology: true  # 包含方法论
  include_limitations: true  # 包含局限性
  include_recommendations: true  # 包含建议
  citation_style: "apa"  # 引用格式: apa, mla, chicago
  max_report_length: 10000  # 最大报告长度

# 质量评估配置
quality_assessment:
  criteria:
    - "completeness"  # 完整性
    - "accuracy"  # 准确性
    - "relevance"  # 相关性
    - "coherence"  # 连贯性
    - "depth"  # 深度
  weights:
    completeness: 0.25
    accuracy: 0.25
    relevance: 0.20
    coherence: 0.15
    depth: 0.15
  min_quality_score: 0.7

# 交互界面配置
interactive:
  enable_real_time_updates: true  # 启用实时更新
  update_interval: 2.0  # 更新间隔(秒)
  enable_user_feedback: true  # 启用用户反馈
  enable_progress_tracking: true  # 启用进度跟踪
  display_intermediate_results: true  # 显示中间结果

# 监控配置
monitoring:
  enable_performance_monitoring: true  # 启用性能监控
  enable_error_tracking: true  # 启用错误跟踪
  enable_usage_analytics: true  # 启用使用分析
  log_level: "INFO"  # 日志级别: DEBUG, INFO, WARNING, ERROR
  metrics_collection_interval: 10.0  # 指标收集间隔(秒)
  enabled: true
  metrics:
    - execution_time
    - search_count
    - loop_count
    - success_rate
    - token_usage
    - quality_score
    - iteration_count

# 缓存配置
caching:
  enable_query_cache: true  # 启用查询缓存
  enable_content_cache: true  # 启用内容缓存
  cache_ttl: 3600  # 缓存生存时间(秒)
  max_cache_size: 1000  # 最大缓存条目数

# 输出配置
output:
  directory: "./output"  # 输出目录
  filename_template: "research_{topic}_{timestamp}"  # 文件名模板
  save_intermediate_results: true  # 保存中间结果
  compress_output: false  # 压缩输出

# 并发配置
concurrency:
  max_concurrent_searches: 3  # 最大并发搜索数
  max_concurrent_analysis: 2  # 最大并发分析数
  request_rate_limit: 10  # 请求速率限制(每秒)
  enable_async_processing: true  # 启用异步处理

# 错误处理配置
error_handling:
  max_retries: 3  # 最大重试次数
  retry_delay: 1.0  # 重试延迟(秒)
  enable_graceful_degradation: true  # 启用优雅降级
  fallback_to_mock: true  # 回退到模拟模式

# 安全配置
security:
  enable_content_filtering: true  # 启用内容过滤
  enable_rate_limiting: true  # 启用速率限制
  sanitize_inputs: true  # 清理输入
  validate_sources: true  # 验证来源