# agenticx-for-intent-recognition 配置文件

# LLM配置
llm:
  provider: openai
  model: gpt-4o-mini
  api_key: ${OPENAI_API_KEY}
  base_url: ${OPENAI_API_BASE}  # 支持代理设置
  temperature: 0.7
  max_tokens: 1000

# 智能体配置
agents:
  - id: main_agent
    name: 主智能体
    role: 助手
    goal: 帮助用户完成任务
    backstory: 我是一个专业的AI助手
    tools: []

# 工作流配置
workflows:
  - id: main_workflow
    name: 主工作流
    nodes:
      - id: start
        type: agent
        agent_id: main_agent
    edges: []

# 监控配置
monitoring:
  enabled: true
  metrics:
    - execution_time
    - token_usage
    - success_rate