# agenticx/rl/mimo_harbor_bridge.py
"""MiMo PooledTask → harbor 任务目录物化（SP23 收尾 / 校准前置）。

把 datasets/task_pool.json 里的任务落成 harbor 可执行目录:
  <out_root>/<org>/<task_id>/
    task.toml          # environment.image = 统一镜像:tag(instance_id)
    instruction.md     # 任务指令（agent 可见）
    tests/test.sh      # 容器内执行: 应用 test_patch → 跑 test_command →
                       #   解析 pytest/jest 输出 → 写 /logs/verifier/reward.txt
    tests/test_patch.diff  # code 域 verifier 测试（SP23 烟测实测: git apply 干净）

code 域 test_command 由 harness 注入（镜像内无脚本, 实测确认）; cyber 域
verifier 预置镜像内, test.sh 只做转调。

镜像拉取（境内）: docker pull docker.1ms.run/xiaomimimo/mimo-v2.6-rl-oss:<tag>
task.toml 用完整域名（docker.io 会被墙, harbor 侧拉取前需 tag 成本地名或
预拉取——本模块提供 mirror_prefix 参数处理）。
"""
from __future__ import annotations

import json
import re
from pathlib import Path

_REPO_POOL = Path(__file__).resolve().parents[3] / "datasets" / "task_pool.json"
if not _REPO_POOL.exists():  # 兼容源码树内直接运行（agenticx/rl/ → 仓库根）
    _REPO_POOL = Path(__file__).resolve().parents[2] / "datasets" / "task_pool.json"

# 境内加速前缀（Docker Hub 直连被墙; SP23 实测 docker.1ms.run 可达）
DEFAULT_MIRROR = "docker.1ms.run"

# agent setup 缓存说明: qemu 模拟层下装 uv+Python+agenticx 需 30min+,
# 通过 trial config 的 environment.mounts 挂宿主缓存目录复用（见
# harbor_reward.AGENT_SETUP_CACHE_MOUNTS——task.toml 的 [environment]
# 不支持 mounts, 实测被忽略）。

_TASK_TOML = '''schema_version = "1.4"
artifacts = []

[task]
name = "{org}/{name}"
version = "1.0.0"
description = "MiMo-V2.6-RL-oss {domain} task (imported)"

[metadata]
domain = "{domain}"
source = "mimo-rl-oss"

[verifier]
timeout_sec = {timeout}
collect = []

[verifier.env]

[agent]
timeout_sec = {agent_timeout}
override_setup_timeout_sec = 3600

[environment]
network_mode = "public"
build_timeout_sec = 600.0
os = "linux"
docker_image = "{image}"
mcp_servers = []

[environment.env]

[solution.env]
'''

# jest 系任务的安全参数: 受限容器内默认并行会 OOM(实测 Killed/137),
# --runInBand 单进程 + --ci 关 watch; 只对含 jest 的命令追加
_JEST_ARGS = "--runInBand --ci"


def _safe_test_command(cmd: str) -> str:
    """test_command 转译: jest 命令追加安全参数, 其余原样。"""
    if "jest" in cmd:
        # 已带参数则不重复加
        if "--runInBand" in cmd or "-i" in cmd.split():
            return cmd
        return cmd.rstrip() + " " + _JEST_ARGS
    return cmd


# code 域: 应用 test_patch（patch 自带 mimo_test_command.sh + 测试文件, 实测
# 确认）→ 注入 jest 安全参数 → 执行 → 判 exit code
# jest 安全参数: 受限容器内裸 npx jest 并行 worker 会 OOM(实测 Killed/137,
# Apple Silicon 模拟层尤甚)——sed 注入 --runInBand --ci 后实测通过
_CODE_TEST_SH = '''#!/bin/bash
# MiMo code-domain verifier (generated by mimo_harbor_bridge)
set -u
export CI=false
cd "{cwd}"

# 1) apply test patch: verifier 测试 + mimo_test_command.sh（patch 自带）
if [ -f /tests/test_patch.diff ]; then
  git apply /tests/test_patch.diff || {{ echo 0 > /logs/verifier/reward.txt; exit 0; }}
fi

# 2) jest 系命令注入单进程参数（防容器 OOM）
if [ -f "{cwd}/mimo_test_command.sh" ]; then
  sed -i 's/npx jest/npx jest --runInBand --ci/g' "{cwd}/mimo_test_command.sh"
fi

# 3) 执行（timeout 保护）
LOG=$(timeout {timeout} bash "{cwd}/mimo_test_command.sh" 2>&1)
RC=$?
echo "$LOG" | tail -50 > /logs/verifier/verifier.log

# 4) verdict: command exit 0 = pass
if [ $RC -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
'''

# cyber 域: verifier 预置镜像内, 转调
_RULE_TEST_SH = '''#!/bin/bash
# MiMo rule-domain verifier passthrough (generated by mimo_harbor_bridge)
set -u
cd "{cwd}"
LOG=$(timeout {timeout} bash -lc "{test_command}" 2>&1)
RC=$?
echo "$LOG" | tail -50 > /logs/verifier/verifier.log
if [ $RC -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
'''


def _safe_name(task_id: str) -> str:
    """task_id → toml 安全的 name（harbor task name 约束: [a-z0-9-]）。"""
    return re.sub(r"[^a-z0-9-]+", "-", task_id.lower()).strip("-")[:80]


def materialize_task(task: dict, out_root: Path, *, org: str = "mimo",
                     mirror: str | None = DEFAULT_MIRROR) -> Path:
    """把池内单任务物化为 harbor 任务目录, 返回目录路径。

    task 字段来自 datasets/task_pool.json 的 tasks[] 条目。
    extras: code 域带 test_patch（含测试 diff）; test_command 在 verifier_ref。
    """
    tid = task["task_id"]
    name = _safe_name(tid)
    domain = task["domain"]
    d = Path(out_root) / org / name
    (d / "tests").mkdir(parents=True, exist_ok=True)

    # 实测镜像形态: 统一仓库 xiaomimimo/mimo-v2.6-rl-oss, tag=instance_id
    # （docker_image 字段形如 "format-code-task-001457:latest", 冒号前是
    # instance_id; 境内加镜像前缀, Docker Hub 直连被墙）
    image = task["docker_image"].removeprefix("docker.io/")
    instance_id = image.split(":")[0]
    unified = f"xiaomimimo/mimo-v2.6-rl-oss:{instance_id}"
    if mirror:
        unified = f"{mirror}/{unified}"
    image = unified

    timeout = int(task.get("extras", {}).get("timeout_sec", 900))
    cfg = _TASK_TOML.format(
        org=org, name=name, domain=domain, image=image,
        timeout=timeout, agent_timeout=max(timeout, 1800))
    (d / "task.toml").write_text(cfg)

    (d / "instruction.md").write_text(task["instruction"] or "")

    test_command = _safe_test_command(task.get("verifier_ref", ""))
    if domain == "code":
        sh = _CODE_TEST_SH.format(cwd=task.get("cwd", "/testbed"),
                                  test_command=test_command,
                                  timeout=timeout)
        patch = task.get("extras", {}).get("test_patch")
        if patch:
            (d / "tests" / "test_patch.diff").write_text(patch)
    else:
        sh = _RULE_TEST_SH.format(cwd=task.get("cwd", "/home/agent"),
                                  test_command=test_command or "true",
                                  timeout=timeout)
    (d / "tests" / "test.sh").write_text(sh)
    return d


def materialize_pool(out_root: Path, *, pool_path: Path = _REPO_POOL,
                     limit: int | None = None,
                     domains: tuple[str, ...] = ("code",),
                     mirror: str | None = DEFAULT_MIRROR) -> list[Path]:
    """批量物化（默认只做 code 域——cyber 的 verifier_ref 是说明文字,
    需要镜像内真实命令才能物化, 校准阶段先跳过）。

    test_patch 内容不在池清单里（只存 has_test_patch 标记）, 物化时
    从 parquet 原表按 instance_id 回查。
    """
    import pandas as pd

    parquet = Path(pool_path).parent / "mimo-rl-oss" / "code.parquet"
    patch_by_id: dict[str, str] = {}
    if parquet.exists() and "code" in domains:
        df = pd.read_parquet(parquet)
        for _, row in df.iterrows():
            info = row["extra_info"]
            if isinstance(info, str):
                info = json.loads(info)
            raw = info.get("instance_json")
            ij = json.loads(raw) if isinstance(raw, str) else raw
            patch_by_id[ij["instance_id"]] = ij.get("test_patch") or ""

    data = json.loads(Path(pool_path).read_text())
    out: list[Path] = []
    for t in data["tasks"]:
        if domains and t["domain"] not in domains:
            continue
        if limit and len(out) >= limit:
            break
        if t["domain"] == "code":
            iid = t["task_id"].removeprefix("code-")
            t = {**t, "extras": {**t.get("extras", {}),
                                 "test_patch": patch_by_id.get(iid, "")}}
        out.append(materialize_task(t, out_root, mirror=mirror))
    return out
